/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cmp16_17 (
    input [5:0] alufn,
    input z,
    input v,
    input n,
    output reg [15:0] compOUT
  );
  
  
  
  always @* begin
    
    case (alufn[1+1-:2])
      2'h1: begin
        compOUT = {15'h0000, z};
      end
      2'h2: begin
        compOUT = {15'h0000, v ^ n};
      end
      2'h3: begin
        compOUT = {15'h0000, z | (v ^ n)};
      end
      default: begin
        compOUT = 1'h0;
      end
    endcase
  end
endmodule
