/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder16_11 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg z,
    output reg v,
    output reg n,
    output reg [15:0] addOUT
  );
  
  
  
  reg [15:0] out;
  
  always @* begin
    out = $signed(a) + $signed(b ^ {5'h10{alufn[0+0-:1]}}) + alufn[0+0-:1];
    addOUT = out;
    z = (~|out);
    v = (a[15+0-:1] & (b[15+0-:1] ^ alufn[0+0-:1]) & ~out[15+0-:1]) | (~a[15+0-:1] & ~(b[15+0-:1] ^ alufn[0+0-:1]) & out[15+0-:1]);
    n = out[15+0-:1];
  end
endmodule
