/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bool16_15 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] boolOUT
  );
  
  
  
  always @* begin
    
    case (alufn[0+3-:4])
      4'h6: begin
        boolOUT = a ^ b;
      end
      4'h8: begin
        boolOUT = a & b;
      end
      4'ha: begin
        boolOUT = a;
      end
      4'he: begin
        boolOUT = a | b;
      end
      default: begin
        boolOUT = 1'h0;
      end
    endcase
  end
endmodule
