/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module muldiv16_18 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg z,
    output reg v,
    output reg n,
    output reg [15:0] muldivOUT
  );
  
  
  
  reg [31:0] out;
  
  always @* begin
    
    case (alufn[1+1-:2])
      2'h1: begin
        out = $signed(a) * $signed(b);
        z = (~|(out[0+15-:16]));
        if (a != 1'h0 && $signed(out[0+15-:16]) / $signed(a) != $signed(b)) begin
          v = 1'h1;
        end else begin
          v = 1'h0;
        end
        n = a[15+0-:1] ^ b[15+0-:1];
      end
      2'h2: begin
        if (b == 1'h0) begin
          out = 1'h0;
          z = 1'h0;
          v = 1'h0;
          n = 1'h0;
        end else begin
          out = $signed(a) / $signed(b);
          z = (~|(out[0+15-:16]));
          n = a[15+0-:1] ^ b[15+0-:1];
          v = 1'h0;
        end
      end
      2'h3: begin
        if (b == 1'h0) begin
          out = 1'h0;
          z = 1'h0;
          v = 1'h0;
          n = 1'h0;
        end else begin
          out = a - (a / b * b);
          z = (~|(out[0+15-:16]));
          n = out[15+0-:1];
          v = 1'h0;
        end
      end
      default: begin
        out = 1'h0;
        z = 1'h0;
        v = 1'h0;
        n = 1'h0;
      end
    endcase
    muldivOUT = out[0+15-:16];
  end
endmodule
